# Generated by Django 3.2 on 2025-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_attachment',
            field=models.BooleanField(default=False, verbose_name='دارای پیوست'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='هرزنامه'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='ستاره\u200cدار'),
        ),
    ]
