# Generated by Django 5.1.6 on 2025-02-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advplatform', '0024_alter_campaign_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposes', models.TextField(verbose_name='پیشنهادات شما')),
                ('purposed_price', models.BigIntegerField(verbose_name='قیمت پیشنهادی')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_campaign', to='advplatform.campaign', verbose_name='کمپین')),
                ('dealer', models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participate', to=settings.AUTH_USER_MODEL, verbose_name='شرکت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش های کمپین',
                'verbose_name_plural': 'تراکنش های کمپین ها',
            },
        ),
        migrations.CreateModel(
            name='EditingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('edit_reason', models.TextField(verbose_name='موارد ویرایش')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_campaign', to='advplatform.campaign', verbose_name='کمپین')),
                ('submitted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'ویرایش های کمپین',
                'verbose_name_plural': 'ویرایش های کمپین ها',
            },
        ),
    ]
