# Generated by Django 3.2 on 2025-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('proposals', models.TextField(verbose_name='پیشنهادات شما')),
                ('proposal_price', models.BigIntegerField(verbose_name='قیمت پیشنهادی')),
            ],
            options={
                'verbose_name': 'تراکنش های کمپین',
                'verbose_name_plural': 'تراکنش های کمپین ها',
            },
        ),
        migrations.CreateModel(
            name='EditingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('edit_reason', models.TextField(verbose_name='موارد ویرایش')),
            ],
            options={
                'verbose_name': 'ویرایش های کمپین',
                'verbose_name_plural': 'ویرایش های کمپین ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestForMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('', ''), ('pending', 'در حال بررسی'), ('approved', 'تایید'), ('reject', 'عدم تایید')], default='pending', max_length=30, verbose_name='وضعیت درخواست')),
            ],
            options={
                'verbose_name': 'درخواست مشاور',
                'verbose_name_plural': 'درخواست های مشاور',
                'ordering': ['-created_at'],
            },
        ),
    ]
