# Generated by Django 3.2 on 2025-05-31 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advplatform', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestformentor',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editingcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editings', to='advplatform.campaign', verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='editingcampaign',
            name='submitted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش کننده'),
        ),
        migrations.AddField(
            model_name='campaigntransaction',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_campaign', to='advplatform.campaign', verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='campaigntransaction',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participate', to=settings.AUTH_USER_MODEL, verbose_name='شرکت کننده'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntransaction',
            unique_together={('dealer', 'campaign')},
        ),
    ]
