# Generated by Django 5.1.6 on 2025-02-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('advplatform', '0024_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editingcampaign',
            options={'ordering': ['-created_time'], 'verbose_name': 'ویرایش های کمپین', 'verbose_name_plural': 'ویرایش های کمپین ها'},
        ),
        migrations.AlterField(
            model_name='editingcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editings', to='advplatform.campaign', verbose_name='کمپین'),
        ),
    ]
