# Generated by Django 5.1.6 on 2025-02-18 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_editingcampaign_options_and_more'),
        ('advplatform', '0024_alter_campaign_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaigntransaction',
            unique_together={('dealer', 'campaign')},
        ),
    ]
