# Generated by Django 5.1.6 on 2025-02-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_campaigntransaction_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigntransaction',
            old_name='purposed_price',
            new_name='proposal_price',
        ),
        migrations.RenameField(
            model_name='campaigntransaction',
            old_name='purposes',
            new_name='proposals',
        ),
    ]
