# Generated by Django 5.1.6 on 2025-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_requestformentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformentor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestformentor',
            name='status',
            field=models.CharField(choices=[('', ''), ('pending', 'در حال بررسی'), ('accept', 'تایید'), ('reject', 'عدم تایید')], default='pending', max_length=30, verbose_name='وضعیت درخواست'),
        ),
    ]
