version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Prevent deletion of data after restart

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:secretpassword@db:5432/advertisement_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: