# Generated by Django 3.2 on 2025-01-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstarctUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField()),
                ('purposed_price', models.BigIntegerField(default=0)),
                ('starttimedate', models.DateTimeField(blank=True, null=True)),
                ('endtimedate', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('done_time', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('abstarctuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advplatform.abstarctuser')),
                ('bussines_value', models.BigIntegerField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Juridical'), (2, 'Private')])),
            ],
            bases=('advplatform.abstarctuser',),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('abstarctuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advplatform.abstarctuser')),
                ('rank', models.SmallIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Corporate'), (2, 'Influencer'), (3, 'Private Designer')])),
            ],
            bases=('advplatform.abstarctuser',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('abstarctuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advplatform.abstarctuser')),
                ('rank', models.SmallIntegerField(default=0)),
            ],
            bases=('advplatform.abstarctuser',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advplatform.topic')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioimages', to='advplatform.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advplatform.topic'),
        ),
        migrations.CreateModel(
            name='CampaignImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/')),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaignsimages', to='advplatform.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='topic',
            field=models.ManyToManyField(to='advplatform.Topic'),
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advplatform.activitycategory')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advplatform.dealer'),
        ),
        migrations.CreateModel(
            name='MentorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mentors/')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorimages', to='advplatform.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='DealerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dealers/')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealerimages', to='advplatform.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customers/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerimages', to='advplatform.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_mentor',
            field=models.ManyToManyField(blank=True, to='advplatform.Mentor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='field_of_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advplatform.activitycategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advplatform.customer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='list_of_participants',
            field=models.ManyToManyField(blank=True, to='advplatform.Dealer'),
        ),
    ]
