# Generated by Django 3.2 on 2025-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
