# Generated by Django 3.2 on 2025-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'verbose_name': 'Activity Category', 'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
