# Generated by Django 3.2 on 2025-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0002_auto_20250128_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
