# Generated by Django 3.2 on 2025-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0002_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='finished_review',
            field=models.BooleanField(default=False, verbose_name='وضعیت تعیین برنده'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('reviewing', 'در حال بررسی'), ('progressing', 'در حال برگزاری'), ('unsuccessful', 'ناموفق'), ('successful', 'موفق'), ('editing', 'اصلاح مشتری'), ('cancel', 'انصراف مشتری'), ('finished', 'پایان یافته')], default='reviewing', max_length=30, verbose_name='وضعیت اجرای کمپین'),
        ),
    ]
