# Generated by Django 3.2 on 2025-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0003_alter_activitycategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
