# Generated by Django 3.2 on 2025-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0003_auto_20250626_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('reviewing', 'در حال بررسی'), ('progressing', 'در حال برگزاری'), ('unsuccessful', 'ناموفق'), ('successful', 'موفق'), ('editing', 'اصلاح مشتری'), ('cancel', 'انصراف مشتری'), ('finished', 'پایان یافته')], default='unpaid', max_length=30, verbose_name='وضعیت اجرای کمپین'),
        ),
    ]
