# Generated by Django 3.2 on 2025-02-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0003_auto_20250205_1853'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
