# Generated by Django 5.0.14 on 2025-07-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0004_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('reviewing', 'در حال بررسی'), ('progressing', 'در حال برگزاری'), ('unsuccessful', 'ناموفق'), ('successful', 'موفق'), ('editing', 'اصلاح مشتری'), ('cancel', 'انصراف مشتری'), ('finished', 'پایان یافته'), ('unpaid', 'منتظر پرداخت')], default='unpaid', max_length=30, verbose_name='وضعیت اجرای کمپین'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'مشتری'), ('dealer', 'عامل تبلیغ'), ('mentor', 'مشاور')], default='', max_length=30, null=True, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رزومه')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/files/', verbose_name='فایل رزومه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('edited', 'ویرایش شده توسط مدیر')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='نظر مدیر')),
                ('is_seen_by_manager', models.BooleanField(default=False, verbose_name='مشاهده شده توسط مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='مجری کمپین')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
