# Generated by Django 3.2 on 2025-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='1', max_length=30, null=True),
        ),
    ]
