# Generated by Django 3.2 on 2025-01-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_mentor',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_mentor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='advplatform.mentor'),
        ),
    ]
