# Generated by Django 5.0.14 on 2025-07-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0005_alter_campaign_status_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزومه', 'verbose_name_plural': 'رزومه ها'},
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
