# Generated by Django 3.2 on 2025-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignimages',
            options={'verbose_name': 'عکس کمپین', 'verbose_name_plural': 'عکس های کمپین'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimages',
            options={'verbose_name': 'عکس نمونه کار', 'verbose_name_plural': 'عکس های نمونه کارها'},
        ),
        migrations.AlterModelOptions(
            name='usersimages',
            options={'verbose_name': 'عکس کاربر', 'verbose_name_plural': 'عکس های کاربر'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
