# Generated by Django 3.2 on 2025-01-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0005_auto_20250128_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_mentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='advplatform.mentor'),
        ),
    ]
