# Generated by Django 5.0.14 on 2025-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0006_alter_resume_options_topic_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='short_describe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
