# Generated by Django 3.2 on 2025-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0007_alter_campaign_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dealer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
