# Generated by Django 3.2 on 2025-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0007_alter_customer_customer_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
