# Generated by Django 5.0.14 on 2025-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0007_topic_short_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='short_describe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
