# Generated by Django 5.0.14 on 2025-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0008_alter_topic_short_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'مشتری'), ('dealer', 'عامل تبلیغ')], default='', max_length=30, null=True, verbose_name='نوع کاربر'),
        ),
    ]
