# Generated by Django 5.0.14 on 2025-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0009_customuser_company_name_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cutomer_type',
            field=models.CharField(blank=True, choices=[('private', 'حقیقی'), ('juridical', 'حقوقی')], default='', max_length=30, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'مجری تبلیغ'), ('dealer', 'سفارش دهنده تبلیغ')], default='', max_length=30, null=True, verbose_name='نوع کاربر'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
