# Generated by Django 3.2 on 2025-01-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0009_auto_20250130_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='speciality_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='advplatform.specialitycategory'),
        ),
    ]
