# Generated by Django 3.2 on 2025-01-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0010_mentor_speciality_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='speciality_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advplatform.specialitycategory'),
        ),
    ]
