# Generated by Django 5.0.14 on 2025-08-05 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0010_alter_customuser_cutomer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='bank_account',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='شماره حساب بانکی'),
        ),
        migrations.AddField(
            model_name='resume',
            name='dealer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_type', to='advplatform.topic', verbose_name='نوع مجری تبلیغات'),
        ),
        migrations.AddField(
            model_name='resume',
            name='partner_brand',
            field=models.TextField(blank=True, null=True, verbose_name='برند همکار'),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolios',
            field=models.ManyToManyField(blank=True, to='advplatform.portfolio', verbose_name='پورتفولیوها'),
        ),
        migrations.AddField(
            model_name='resume',
            name='services',
            field=models.TextField(blank=True, null=True, verbose_name='خدمات قابل ارائه'),
        ),
        migrations.AddField(
            model_name='resume',
            name='socialmedia_and_sites',
            field=models.TextField(blank=True, null=True, verbose_name='شبکه\u200cهای اجتماعی و وب\u200cسایت\u200cها'),
        ),
        migrations.AddField(
            model_name='resume',
            name='specialty_categories',
            field=models.ManyToManyField(related_name='specialty_categories', to='advplatform.topic', verbose_name='دسته\u200cهای تخصصی'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tools_and_platforms',
            field=models.TextField(blank=True, null=True, verbose_name='ابزارها و پلتفرم\u200cها'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('dealer', 'مجری تبلیغ'), ('customer', 'سفارش دهنده تبلیغ')], default='', max_length=30, null=True, verbose_name='نوع کاربر'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان رزومه'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر صاحب رزومه'),
        ),
        migrations.AddField(
            model_name='resume',
            name='service_area',
            field=models.ManyToManyField(help_text='شهرهایی که در آن\u200cها خدمات ارائه می\u200cدهید', related_name='resumes', to='advplatform.city', verbose_name='حوزه خدمات (شهرها)'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='مثل: مجوز کسب، گواهینامه، پروانه فعالیت', max_length=100, verbose_name='عنوان مجوز')),
                ('file', models.FileField(help_text='فرمت\u200cهای مجاز: PDF, JPG, PNG', upload_to='resumes/permissions/', verbose_name='فایل مجوز')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی در مورد این مجوز', null=True, verbose_name='توضیحات')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('issuing_authority', models.CharField(blank=True, max_length=150, null=True, verbose_name='مرجع صادرکننده')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_files', to='advplatform.resume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='advplatform.province', verbose_name='استان'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان یا توضیح کوتاه نمونه کار', max_length=100, verbose_name='عنوان نمونه کار')),
                ('url', models.URLField(help_text='آدرس کامل نمونه کار (مثل: https://example.com)', verbose_name='آدرس لینک')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی در مورد این نمونه کار', null=True, verbose_name='توضیحات')),
                ('category', models.CharField(blank=True, help_text='نوع نمونه کار (مثل: وب\u200cسایت، اپلیکیشن، طراحی گرافیک)', max_length=50, null=True, verbose_name='دسته\u200cبندی')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('is_featured', models.BooleanField(default=False, help_text='آیا این نمونه کار به عنوان کار برجسته نمایش داده شود؟', verbose_name='نمونه کار برجسته')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش این لینک (عدد کمتر اولویت بالاتر)', verbose_name='ترتیب نمایش')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_links', to='advplatform.resume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'لینک نمونه کار',
                'verbose_name_plural': 'لینک\u200cهای نمونه کارها',
                'ordering': ['order', '-is_featured', '-created_at'],
                'unique_together': {('resume', 'url')},
            },
        ),
    ]
