# Generated by Django 3.2 on 2025-02-06 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0011_alter_campaign_campaign_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
