# Generated by Django 3.2 on 2025-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0011_alter_mentor_speciality_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='list_of_participants',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='advplatform.Dealer'),
        ),
    ]
