# Generated by Django 5.0.14 on 2025-08-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0012_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dealer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_type', to='advplatform.topic', verbose_name='نوع مجری تبلیغات'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='describe',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='services',
            field=models.TextField(verbose_name='خدمات قابل ارائه'),
        ),
    ]
