# Generated by Django 5.0.14 on 2025-08-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0013_alter_resume_dealer_type_alter_resume_describe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='specialty_categories',
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('under_review', 'در حال بررسی'), ('needs_editing', 'نیاز به ویرایش'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='resume',
            name='specialty_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialty_categories', to='advplatform.topic', verbose_name='دسته\u200cهای تخصصی'),
        ),
    ]
