# Generated by Django 5.1.6 on 2025-02-10 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0013_portfolio_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to=settings.AUTH_USER_MODEL, verbose_name='نام مجری'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح نمونه کار'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='done_time',
            field=models.DateField(verbose_name='زمان انجام'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان نمونه کار'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advplatform.topic', verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to='portfolios/', verbose_name='عکس های نمونه کار'),
        ),
    ]
