# Generated by Django 5.0.14 on 2025-08-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0014_remove_resume_specialty_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dealer_type',
            field=models.ForeignKey(error_messages={'null': 'لطفاً نوع مجری تبلیغات را انتخاب کنید.'}, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_type', to='advplatform.topic', verbose_name='نوع مجری تبلیغات'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='describe',
            field=models.TextField(verbose_name='معرفی مختصر از خود'),
        ),
    ]
