# Generated by Django 5.1.6 on 2025-02-10 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0014_alter_portfolio_dealer_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bussines_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customer_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_customers', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cutomer_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dealer_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع عامل تبلیغ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='field_of_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advplatform.activitycategory', verbose_name='زمینه فعالیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='رتبه بندی(۵)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speciality_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advplatform.specialitycategory', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع کاربر'),
        ),
    ]
