# Generated by Django 5.0.14 on 2025-08-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0015_alter_resume_dealer_type_alter_resume_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dealer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_type', to='advplatform.topic', verbose_name='نوع مجری تبلیغات'),
        ),
    ]
