# Generated by Django 5.1.6 on 2025-02-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0015_alter_customuser_address_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bussines_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ارزش کسب و کار'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, help_text='حتماً باید نوع کاربر مشخص شود و این موجودیت بعد از ثبت نام قابل تغییر نیست', max_length=50, null=True, verbose_name='نوع کاربر'),
        ),
    ]
