# Generated by Django 5.1.6 on 2025-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0016_alter_customuser_bussines_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', ''), ('customer', 'مشتری'), ('dealer', 'عامل تبلیغ'), ('mentor', 'مشاور')], default='', max_length=50, null=True, verbose_name='نوع کاربر'),
        ),
    ]
