# Generated by Django 5.0.14 on 2025-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0016_alter_resume_dealer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolios',
            field=models.ManyToManyField(blank=True, null=True, to='advplatform.portfolio', verbose_name='پورتفولیوها'),
        ),
    ]
