# Generated by Django 5.0.14 on 2025-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0017_alter_resume_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='speciality_field',
            field=models.ManyToManyField(blank=True, related_name='speciality_field', to='advplatform.topic', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolios',
            field=models.ManyToManyField(blank=True, to='advplatform.portfolio', verbose_name='پورتفولیوها'),
        ),
    ]
