# Generated by Django 5.1.6 on 2025-02-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cutomer_type',
            field=models.CharField(blank=True, choices=[('', ''), ('juridical', 'حقیقی'), ('private', 'حقوقی')], default='', max_length=30, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dealer_type',
            field=models.CharField(blank=True, choices=[('', ''), ('influencer', 'اینفلوئنسر '), ('private_designer', 'شخص عادی'), ('corporate', 'شرکت')], default='', max_length=30, null=True, verbose_name='نوع عامل تبلیغ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', ''), ('customer', 'مشتری'), ('dealer', 'عامل تبلیغ'), ('mentor', 'مشاور')], default='', max_length=30, null=True, verbose_name='نوع کاربر'),
        ),
    ]
