# Generated by Django 5.0.14 on 2025-08-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0018_alter_customuser_speciality_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialty_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_categories', to='advplatform.topic', verbose_name='دسته\u200cهای تخصصی'),
        ),
    ]
