# Generated by Django 5.1.6 on 2025-02-14 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0018_alter_customuser_cutomer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='execution_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='هزینه اجرا'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_dealers', to=settings.AUTH_USER_MODEL, verbose_name='مجرب ی کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مهلت اجرا'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='describe',
            field=models.TextField(verbose_name='شرح کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='endtimedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='list_of_participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'user_type': 'dealer'}, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='لیست شرکت کنندگان'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='purposed_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='starttimedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت اجرای کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='topic',
            field=models.ManyToManyField(to='advplatform.topic', verbose_name='موضوعات کمپین'),
        ),
    ]
