# Generated by Django 5.0.14 on 2025-08-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0019_alter_resume_specialty_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='انتخاب شده برای نمایش'),
        ),
    ]
