# Generated by Django 5.1.6 on 2025-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0020_alter_campaign_campaign_dealer_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت کمپین'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='purposed_price',
            field=models.BigIntegerField(default=1, verbose_name='قیمت پیشنهادی'),
            preserve_default=False,
        ),
    ]
