# Generated by Django 5.1.6 on 2025-02-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0021_alter_campaign_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='publish_status',
            field=models.CharField(choices=[('p', 'منتشرشده'), ('d', 'پیش نویس')], default='d', max_length=3, verbose_name='وضعیت انتشار کمپین'),
        ),
    ]
