# Generated by Django 5.1.6 on 2025-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0022_campaign_publish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='publish_status',
        ),
    ]
