# Generated by Django 5.1.6 on 2025-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0023_remove_campaign_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('reviewing', 'در حال بررسی'), ('progressing', 'در حال برگزاری'), ('unsuccessful', 'ناموفق'), ('successful', 'موفق'), ('editing', 'اصلاح مشتری'), ('cancel', 'انصراف مشتری')], default='reviewing', max_length=30, verbose_name='وضعیت اجرای کمپین'),
        ),
    ]
