# Generated by Django 5.1.6 on 2025-02-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0024_alter_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivityFiled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advplatform.customeractivityfiled')),
            ],
            options={
                'verbose_name': 'دسته بندی دسته کاری',
                'verbose_name_plural': 'دسته بندی های دسته کاری',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='customer_field_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advplatform.customeractivityfiled', verbose_name='زمینه کسب و کار'),
        ),
    ]
