# Generated by Django 5.1.6 on 2025-02-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0025_customeractivityfiled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='customer_field_activity',
        ),
        migrations.DeleteModel(
            name='CustomerActivityFiled',
        ),
    ]
