# Generated by Django 5.1.6 on 2025-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0026_remove_customuser_customer_field_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='شماره تماس'),
        ),
    ]
