# Generated by Django 5.1.6 on 2025-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0028_alter_campaign_options_alter_campaign_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_time'], 'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterField(
            model_name='campaignimages',
            name='image',
            field=models.ImageField(upload_to='campaigns/', verbose_name='آپلود تصویر کمپین'),
        ),
    ]
