# Generated by Django 3.2 on 2025-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0029_alter_portfolio_options_alter_campaignimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_am',
            field=models.BooleanField(default=False, verbose_name='مدیر تبلیغات'),
        ),
    ]
