# Generated by Django 3.2 on 2025-04-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0030_customuser_is_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='customer_mentor',
        ),
    ]
