# Generated by Django 3.2 on 2025-04-26 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0031_remove_customuser_customer_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='مشاور اختصاص داده شده'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='needs_mentor',
            field=models.BooleanField(default=False, verbose_name='نیاز به مشاور'),
        ),
    ]
