# Generated by Django 3.2 on 2025-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0033_alter_campaign_needs_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='topics/', verbose_name='آیکون'),
        ),
    ]
