# Generated by Django 3.2 on 2025-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advplatform', '0034_topic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='min_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حداقل قیمت'),
        ),
    ]
