from django.urls import path
from django.conf.urls import handler404
from account.views import (
    AccountView,
    CampaignEditProposalView,
    ChangeStatusRequestForMentor,
    CampaignActivateView,
    CampaignCancelParticipateView,
    CampaignCancelView,
    CampaignCreateView,
    CampaignDeactivateView,
    CampaignDeleteView,
    CampaignEditView,
    CampaignParticipateView,
    CampaignReviewView,
    CampaignListView,
    CustomerResumeView,
    FinishedCampaignProposalDetail,
    ListOfRequestForMentor,
    MentorChooseView,
    MentorUsersList,
    MentorsList,
    MyMentor,
    NewMentorActivate,
    NotificationDetailView,
    NotificationsView,
    PasswordChange,
    PasswordChangeDone, 
    PortfolioCreateView,
    PortfolioDeleteView, 
    PortfolioEditView, 
    PortfolioListView,
    ProfileView,
    CampaignConfirmMentorView,
    ResumeDeleteView,
    ResumeDetailView,
    ResumeReviewListView,
    RunningCampaignParticipatedListView,
    FinishedCampaignProposalsListView,
    SelectCampaignWinnerView,
    UserDetailView,
    UsersList,
    WinnedProposalDetail,
    MyResumeView,
    ajax_add_permission,
    ajax_add_portfolio,
    ajax_add_worklink,  # View جدید برای مشاهده رزومه کاربر
    get_specialty_categories,  # View جدید برای دریافت دسته‌بندی‌های تخصصی
    ProposalDetailView,
    CitiesByProvinceView,
)
from advplatform.views import custom_404_view


app_name = 'account'

handler404 = custom_404_view


urlpatterns = [
    path('', AccountView.as_view(), name='home'),
    path('notifications/', NotificationsView.as_view(), name='notifications_list'),
    path('notifications/detail/<int:pk>', NotificationDetailView.as_view(), name='notifications_detail'),
    path('profile/', ProfileView.as_view(), name='profile'), 
    path('password_change/', PasswordChange.as_view(), name='password_change'), 
    path('password_change/done/', PasswordChangeDone.as_view(), name='password_change_done'), 
    path('portfolios/', PortfolioListView.as_view(), name='portfolios'), 
    path('portfolios/create', PortfolioCreateView.as_view(), name='portfoliocreate'), 
    path('portfolios/edit/<int:pk>', PortfolioEditView.as_view(), name='portfolioedit'), 
    path('portfolios/delete/<int:pk>', PortfolioDeleteView.as_view(), name='portfoliodelete'), 
    path('campaigns/', CampaignListView.as_view(), name='campaigns'), 
    path('campaigns/create/', CampaignCreateView.as_view(), name='campaigncreate'),
    path('campaigns/confirm-mentor/<int:pk>', CampaignConfirmMentorView.as_view(), name='confirm_mentor'),
    path('campaigns/delete/<int:pk>', CampaignDeleteView.as_view(), name='campaignsdelete'), 
    path('campaigns/deactive/<int:pk>', CampaignDeactivateView.as_view(), name='deactivecampaign'), 
    path('campaigns/active/<int:pk>', CampaignActivateView.as_view(), name='activecampaign'), 
    path('campaigns/cancel/<int:pk>', CampaignCancelView.as_view(), name='cancelcampaign'), 
    path('campaigns/review/<int:pk>', CampaignReviewView.as_view(), name='reviewcampaign'), 
    path('campaigns/edit/<int:pk>', CampaignEditView.as_view(), name='campaignedit'),
    path('campaigns/participate/<int:pk>', CampaignParticipateView.as_view(), name='campaignparticipate'),
    path('campaigns/cancelparticipate/<int:pk>', CampaignCancelParticipateView.as_view(), name='cancelcampaignparticipate'), 
    path('campaigns/editproposal/<int:pk>', CampaignEditProposalView.as_view(), name='editproposal'),
    path('campaigns/running-campaign-participated/<int:pk>', RunningCampaignParticipatedListView.as_view(), name='runningcampaignparticipated'),
    path('campaigns/finished-proposals/<int:pk>/', FinishedCampaignProposalsListView.as_view(), name='finished_campaign_proposals'),
    path('campaigns/select-winner/<int:campaign_id>/<int:dealer_id>/', SelectCampaignWinnerView.as_view(), name='select_winner'),
    path('campaigns/finished-proposals/viewdetial/<int:pk>/', WinnedProposalDetail.as_view(), name='winned_proposal_detail'),
    path('mentoruserslist/', MentorUsersList.as_view(), name='mentoruserslist'), 
    path('mymentor/', MyMentor.as_view(), name='mymentor'), 
    path('mentorslist/', MentorsList.as_view(), name='mentorslist'), 
    path('mentor/choosementor/<int:pk>', MentorChooseView.as_view(), name='choosementor'), 
    path('mentor/activementor/<int:pk>', NewMentorActivate.as_view(), name='activementor'), 
    path('requestformentor/', ListOfRequestForMentor.as_view(), name='listofrequestformentor'), 
    path('requestformentor/<int:request_id>/change-status/', ChangeStatusRequestForMentor.as_view(), name='changestatusrequestformentor'),  
    path('resume/my-resume/', MyResumeView.as_view(), name='my_resume'),  # URL جدید
    path('resume/review/', ResumeReviewListView.as_view(), name='review_resumes'),  # برای مدیران
    path('resume/review/<int:resume_id>/', ResumeDetailView.as_view(), name='resume_detail'),  # برای مدیران
    path('get-specialty-categories/', get_specialty_categories, name='get_specialty_categories'),
    path('portfolio/ajax-add/', ajax_add_portfolio, name='portfolio_ajax_add'),
    path('resume/permission/ajax-add/', ajax_add_permission, name='permission_ajax_add'),
    path('resume/worklink/ajax-add/', ajax_add_worklink, name='worklink_ajax_add'),
    path('userslist/', UsersList.as_view(), name='userslist'),
    path('userslist/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('campaigns/proposal/<str:kind>/<int:obj_id>/', ProposalDetailView.as_view(), name='proposal_detail'),
    path('ajax/cities/', CitiesByProvinceView.as_view(), name='ajax_cities'),
    path('resume/customerview/<int:pk>/<int:user_id>/', CustomerResumeView.as_view(), name='dealer_resume'),
    path('campaigns/finished-proposals/proposaldetail/<str:category>/<int:pk>/', FinishedCampaignProposalDetail.as_view(), name='finished_campaign_proposal_detail'),
]