# Generated by Django 3.2 on 2025-06-30 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_paymentreceipt_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
