# Generated by Django 3.2 on 2025-06-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_amount',
        ),
    ]
